pipeline {
    agent none
    stages {
       
                stage('Build Application') {
                    agent {
                     label 'master'   
                    }
                    steps {
                        sh 'mvn -f java-tomcat-sample/pom.xml clean package'
                    }
                    post {
                        success {
                            echo "Now Archiving the Artifacts...."
                            archiveArtifacts artifacts: '**/*.war'
                        }
                    }
                }
        
        /*
        stage('Deploy in Staging Environment'){
            steps{
                build job: 'deploy-on-qa'

            }
            
        }
        */
        /*
       stage('Deploy to Production'){
            steps{
                timeout(time:5, unit:'DAYS'){
                    input message:'Approve PRODUCTION Deployment?'
                }
                build job: 'deploy-to-prd'
            }
        }
        */
        
    }
}
